Complain.create(title: 'test title 1', description: 'test description 1', city: 'test city 1', state: 'test state 1', country: 'test country 1', company: 'test company 1')
Complain.create(title: 'test title 2', description: 'test description 3', city: 'test city 1', state: 'test state 2', country: 'test country 2', company: 'test company 2')
Complain.create(title: 'test title 2', description: 'test description 3', city: 'test city 2', state: 'test state 3', country: 'test country 3', company: 'test company 3')
Complain.create(title: 'test title 2', description: 'test description 3', city: 'test city 2', state: 'test state 4', country: 'test country 4', company: 'test company 4')
Complain.create(title: 'test title 2', description: 'test description 3', city: 'test city 2', state: 'test state 5', country: 'test country 5', company: 'test company 4')
